#!/usr/bin/env node
/**
 * 블로그 동기화 스크립트 — posts.json(SSOT) → index.html·sitemap.xml 자동 갱신
 *
 * 사용법: legal-site/blog/ 에서 `node sync.mjs`
 * 하는 일:
 *   1) blog/index.html 카드 그리드 재생성 (HTML 주석 마커 BLOG-CARDS 사이)
 *   2) blog/index.html JSON-LD Blog 블록 전체 재생성 (<script type="application/ld+json"> 통째 교체 — JSON 내부엔 주석 불가하므로)
 *   3) ../sitemap.xml 블로그 URL 구간 재생성 (XML 주석 마커 BLOG-URLS 사이)
 * 정렬: published 내림차순(최신 먼저). draft:true 항목은 목록·사이트맵에서 제외.
 *
 * 새 글 추가 절차: (1) blog/<slug>.html 작성 (2) posts.json 항목 추가 (3) node sync.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const BLOG_DIR = __dirname;
const SITE = 'https://my-today.net';

function replaceBetween(src, name, inner) {
  const start = `<!-- ${name}:START (auto-generated by sync.mjs — 직접 수정 금지) -->`;
  const end = `<!-- ${name}:END -->`;
  const si = src.indexOf(start);
  const ei = src.indexOf(end);
  if (si === -1 || ei === -1) throw new Error(`마커 ${name} 를 찾을 수 없습니다.`);
  return src.slice(0, si + start.length) + '\n' + inner + '\n  ' + src.slice(ei);
}

const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const fmtDot = (iso) => iso.replace(/-/g, '.');

function main() {
  const data = JSON.parse(readFileSync(join(BLOG_DIR, 'posts.json'), 'utf8'));
  const lastmod = data.lastmod || new Date().toISOString().slice(0, 10);
  const posts = data.posts
    .filter((p) => !p.draft)
    .slice()
    .sort((a, b) => (a.published < b.published ? 1 : a.published > b.published ? -1 : 0));

  // ── 1) 카드 그리드 (HTML — 주석 마커 사용 가능) ──
  const cards = posts.map((p) => {
    const catClass = p.cat === 'todo' ? 'cat' : `cat ${p.cat}`;
    return `
  <a href="./${p.slug}.html" class="blog-card">
    <span class="${catClass}">${esc(p.catLabel)}</span>
    <div class="emoji">${p.emoji}</div>
    <h2>${esc(p.title)}</h2>
    <p>${esc(p.excerpt)}</p>
    <div class="meta">
      <span class="date">${fmtDot(p.published)}</span>
      <span class="more">읽어보기 →</span>
    </div>
  </a>`;
  }).join('\n');

  // ── 2) JSON-LD Blog 블록 전체 (JSON 내부엔 주석 불가 → <script> 통째 교체) ──
  const blogLd = {
    '@context': 'https://schema.org',
    '@type': 'Blog',
    name: 'myToday 블로그',
    description: '기분 기록, 할 일·습관 관리, 마음 습관 만들기, 앱 활용 가이드',
    url: `${SITE}/blog/`,
    publisher: { '@type': 'Organization', name: 'myToday', url: SITE },
    blogPost: posts.map((p) => ({
      '@type': 'BlogPosting',
      headline: p.title,
      url: `${SITE}/blog/${p.slug}.html`,
      datePublished: p.published,
    })),
  };
  const ldScript = `<script type="application/ld+json">\n${JSON.stringify(blogLd, null, 2)}\n</script>`;

  // ── 3) sitemap 블로그 URL (XML — 주석 마커 사용 가능) ──
  const urls = posts.map((p) => `  <url>
    <loc>${SITE}/blog/${p.slug}.html</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>`).join('\n');

  // ── index.html 갱신 ──
  const indexPath = join(BLOG_DIR, 'index.html');
  let html = readFileSync(indexPath, 'utf8');
  html = replaceBetween(html, 'BLOG-CARDS', cards + '\n');
  // JSON-LD: 첫 ld+json script 블록만 교체 (Blog 타입)
  html = html.replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>/, ldScript);
  writeFileSync(indexPath, html, 'utf8');

  // ── sitemap.xml 갱신 ──
  const smPath = join(BLOG_DIR, '..', 'sitemap.xml');
  let sm = readFileSync(smPath, 'utf8');
  sm = replaceBetween(sm, 'BLOG-URLS', urls);
  writeFileSync(smPath, sm, 'utf8');

  console.log(`✅ 동기화 완료: ${posts.length}편 (index.html 카드+JSON-LD, sitemap.xml)`);
  posts.forEach((p, i) => console.log(`   ${i + 1}. [${p.catLabel}] ${p.slug} (${p.published})`));
}

main();
